apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: confluence
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      run: confluence
    name: confluence
  spec:
    replicas: 1
    selector:
      run: confluence
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          run: confluence
      spec:
        containers:
        - env:
            - name: JVM_XMX
              value: '2048m'
            - name: JVM_XMS
              value: '1024m'
          image: docker.io/xhuaustc/confluence:6.7.1
          imagePullPolicy: IfNotPresent
          name: confluence
          volumeMounts:
          - mountPath: /var/atlassian/confluence
            name: volume-7iy6x
          - mountPath: /opt/atlassian/confluence/logs
            name: volume-zsyly
        volumes:
        - name: volume-7iy6x
          persistentVolumeClaim:
            claimName: confluence
        - name: volume-zsyly
          persistentVolumeClaim:
            claimName: log
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      run: mysql
    name: mysql
  spec:
    replicas: 1
    selector:
      run: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          run: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: confluence
          - name: MYSQL_PASSWORD
            value: confluence
          - name: MYSQL_DATABASE
            value: confluence
          - name: MYSQL_ROOT_PASSWORD
            value: confluence
          image: docker.io/xhuaustc/atlassian-mysql:5.7
          imagePullPolicy: IfNotPresent
          name: mysql
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: volume-uiwfa
         volumes:
          - name: volume-uiwfa
            persistentVolumeClaim:
              claimName: mysql-data
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: confluence
    name: confluence
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      run: confluence
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: mysql
    name: mysql
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      run: mysql
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 3000s
    labels:
      run: confluence
    name: confluence
  spec:
    port:
      targetPort: 8090
    to:
      kind: Service
      name: confluence
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ceph-rbd-sc
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
    name: confluence
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ceph-rbd-sc
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
    name: log
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ceph-rbd-sc
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
    name: mysql-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
